plugins:
  extractors:
    - name: tap-postgres
  loaders:
    - name: target-csv--postgres
      inherit_from: target-csv
      config:
        file_naming_scheme: postgres-{datestamp}-{stream_name}.csv
jobs:
  - name: postgres-to-lfs
    tasks:
      - tap-postgres target-csv--postgres
