version: '3'

services:
  db:
    container_name: db
    image: postgres:12
    environment:
      POSTGRES_DB: northwind
      POSTGRES_USER: northwind_user
      POSTGRES_PASSWORD: thewindisblowing
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./data/northwind.sql:/docker-entrypoint-initdb.d/northwind.sql
      - ./scripts/sql:/home/scripts

  analytics-db:
    container_name: analytics-db
    image: postgres
    environment:
      POSTGRES_DB: analytics
      POSTGRES_USER: datanauta
      POSTGRES_PASSWORD: ${OUTPUT_DB_PASSWORD}
    volumes:
      - ./data:/home/data
      - analytics-dbdata:/var/lib/postgresql/data

  server:
    container_name: server
    build: .
    entrypoint: tail -f /dev/null # just to keep container running
    volumes:
      - ./output:/project/output
    env_file:
      - .env

volumes:
  dbdata:
  analytics-dbdata:
