plugins:
  extractors:
    - name: tap-csv--northwind
      inherit_from: tap-csv
      config:
        files:
          - entity: order_details
            path: data/order_details.csv
            keys:
              - order_id
              - product_id
  loaders:
    - name: target-csv--csv
      inherit_from: target-csv
      config:
        file_naming_scheme: csv-{datestamp}-{stream_name}.csv
jobs:
  - name: csv-to-lfs
    tasks:
      - tap-csv--northwind target-csv--csv
